title: ProleSoft
description: Software by and for the proletariat
url: "https://prolesoft.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  -
    values:
      layout: default

theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
paginate: 5
paginate_path: "/blog/page:num"
favicon: /assets/favicon-32x32.png
